// @flow

import { GraphQLEnumType } from 'graphql';

export default new GraphQLEnumType({
  name: 'Language',
  values: {
    ar: { value: 'ar' },
    bg: { value: 'bg' },
    ca: { value: 'ca' },
    cs: { value: 'cs' },
    da: { value: 'da' },
    de: { value: 'de' },
    el: { value: 'el' },
    en: { value: 'en' },
    engb: { value: 'en-gb' },
    enus: { value: 'en-us' },
    es: { value: 'es' },
    esar: { value: 'es-ar' },
    et: { value: 'et' },
    fi: { value: 'fi' },
    fr: { value: 'fr' },
    he: { value: 'he' },
    hr: { value: 'hr' },
    hu: { value: 'hu' },
    id: { value: 'id' },
    is: { value: 'is' },
    it: { value: 'it' },
    ja: { value: 'ja' },
    ko: { value: 'ko' },
    lt: { value: 'lt' },
    lv: { value: 'lv' },
    ms: { value: 'ms' },
    nl: { value: 'nl' },
    no: { value: 'no' },
    pl: { value: 'pl' },
    pt: { value: 'pt' },
    ptbr: { value: 'pt-br' },
    ptpt: { value: 'pt-pt' },
    ro: { value: 'ro' },
    ru: { value: 'ru' },
    sk: { value: 'sk' },
    sl: { value: 'sl' },
    sr: { value: 'sr' },
    sv: { value: 'sv' },
    th: { value: 'th' },
    tl: { value: 'tl' },
    tr: { value: 'tr' },
    uk: { value: 'uk' },
    vi: { value: 'vi' },
    zh: { value: 'zh' },
    zhcn: { value: 'zh-cn' },
    zhtw: { value: 'zh-tw' },
  },
});
